services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - cesaxis_network
networks:
  cesaxis_network:
    external: true