services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
      - WATCHPACK_POLLING=true # Another polling option to ensure file watching
    working_dir: /app