services:
  app:
    image: node:20
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
