name: Continuous Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to repository registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # privilegio para escrever package no registry

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tag: ghcr.io/${github.repository}:${{ github.sha }}
          context: ./churchill
          file: Dockerfile
      
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
        
      - name: Add fingerprint to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 188.166.118.113 >> ~/.ssh/known_hosts

      - name: Deploy to Production Server
        run: |
          ssh -i ~/.ssh/id_prod root@188.166.118.113 "echo Ola!"
