name: Continuous Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to repository registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          context: .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}

      - name: Add fingerprint to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 167.99.222.241 >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        run: |
          ssh root@167.99.222.241 "mkdir -p /srv/frontend"

      - name: Create environment variables
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          ssh root@167.99.222.241 "cat > /srv/frontend/.env << EOL
          GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
          GITHUB_SHA=${GITHUB_SHA}
          EOL"

      - name: Docker compose down
        run: |
          ssh root@167.99.222.241 "cd /srv/frontend && docker compose down || true"

      - name: Copy files to Production Server
        run: |
          scp ./docker-compose.prod.yml root@167.99.222.241:/srv/frontend/docker-compose.yml

      - name: Docker compose up
        run: |
          ssh root@167.99.222.241 "cd /srv/frontend && docker compose up -d"
